### ISSUE TITLE
It's seem that Mesh Out Widget never display in this demo. I just wanna know how to draw custom Mesh.

### ISSUE THREAD

**Issue by CatOnly** [baldurk/renderdoc-contrib#3]
https://github.com/baldurk/renderdoc-contrib/blob/a5db168df5b786971a548d5d430cb12e2f752ec9/baldurk/whereismydraw/window.py#L187

**Comment by baldurk** [comment]
Mesh output isn't used in this extension so you'll need to [read the documentation](https://renderdoc.org/docs/python_api/index.html) if you want to learn how to use it.
